pgm1: main.o sort.o read.o prompt.o print.o
	gcc -o pgm1 main.o sort.o read.o prompt.o print.o
main.o: class.h main.c
	gcc -c main.c
sort.o: class.h sort.c
	gcc -c sort.c
read.o: class.h read.c
	gcc -c read.c
print.o: class.h print.c
	gcc -c print.c
prompt.o: class.h prompt.c
	gcc -c print.c
